name: tbidder_user_app
description: Tbidder Passenger App â€” Transport & Tourism (Peru)
publish_to: "none"
version: 2.0.2+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  permission_handler: ^11.3.1
  flutter_polyline_points: ^2.1.0
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  pdf: ^3.10.7
  share_plus: ^10.0.2
  image_picker: ^1.0.7
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  firebase_crashlytics: ^4.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Both App logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Both App logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
